name: 'Upload Host Info'
description: 'Collect and upload host IP/hostname info'
outputs:
  hostname:
    description: 'Generated file with IP and hostname'
    value: ${{ steps.get-ip-hostname.outputs.hostname }}
runs:
  using: "composite"
  steps:
    - name: Get IP and Hostname
      id: get-ip-hostname
      shell: bash
      run: |
        echo "🔄 Getting IP and hostname for the runner..."
        ip=$(hostname -I | awk '{print $1}')
        hostname=$(hostname)
        echo "IP Hostname: $ip $hostname"
        echo "hostname=$hostname" >> $GITHUB_ENV
        echo "$ip $hostname" > "ip_hostname_${hostname}.txt"
        echo "Generated file: ip_hostname_${hostname}.txt"