name: Install MQTT Mosquitto
description: Install Mosquitto and start the service

runs:
  using: 'composite'
  steps:
    - name: Install Mosquitto
      shell: bash
      run: |
        ${GITHUB_ACTION_PATH}/../../scripts/install_mosquitto.sh