name: Install kafka
description: Install kafka and start the service

runs:
  using: 'composite'
  steps:
    - name: Install kafka
      shell: bash
      run: |
        script_path=$(find $GITHUB_WORKSPACE/../../ -name install_kafka.sh 2>/dev/null | head -n 1)
        chmod +x $script_path
        $script_path