name: Install process-exporter
description: Install process-exporter and start the service

runs:
  using: 'composite'
  steps:
  - name: Check and Install process-exporter
    shell: bash
    run: |
      if [ -f /usr/local/bin/process_exporter ]; then
        echo "process-exporter is already installed."
        # Check if process-exporter is running
        if systemctl is-active --quiet process_exporter; then
          echo "process-exporter is already running."
        else
          echo "process-exporter is not running. Starting the service."
          systemctl start process_exporter
        fi
      else
        echo "process-exporter is not installed. Proceeding with installation."
        # Install process-exporter with setup_env.sh
        wget https://raw.githubusercontent.com/taosdata/TDengine/main/packaging/setup_env.sh
        chmod +x setup_env.sh
        ./setup_env.sh deploy_process_exporter
      fi

  - name: Check process-exporter Status
    shell: bash
    run: |
      STATUS=$(systemctl is-active process_exporter)
      if [ "$STATUS" != "active" ]; then
        echo "::error ::ERROR: process-exporter is in $STATUS state."
        exit 1
      else
        echo "process-exporter is running successfully."
      fi