
name: Install FlashMQ
description: Install FlashMQ and start the service

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install FlashMQ
      shell: bash
      run: |
        chmod +x .github/scripts/install_flashmq.sh
        .github/scripts/install_flashmq.sh