
name: Install FlashMQ
description: Install FlashMQ and start the service

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install FlashMQ
      shell: bash
      run: |
        script_path=$(find $GITHUB_WORKSPACE/../../ -name install_flashmq.sh 2>/dev/null | head -n 1)
        chmod +x $script_path
        $script_path