name: 'Add label for each pr'
inputs:
  github-token:
    description: 'GitHub access token'
    required: true
    default: 'A secret'

runs:
  using: "composite"
  steps:
    - name: Add Team Labels
      uses: actions/github-script@v6
      with:
        github-token: ${{ inputs.github-token }}
        script: |
          console.log('Current working directory:', __dirname);
          const addLabels = require('./add-pr-labels.js');
          await addLabels({ github, context });
