name: 'Auto Add Runner Label'
inputs:
  gh_token:
    description: 'GitHub access token'
    required: true
    default: 'A secret'
  labels:
    description: 'Comma-separated labels'
    required: true
  runner_name:
    description: 'Runner name'
    required: true
runs:
  using: "composite"
  steps:
    - name: Auto Add Runner Label
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      run: |
        response=$(curl -sS -H "Authorization: Bearer ${{ inputs.gh_token }}" \
          "https://api.github.com/orgs/taosdata/actions/runners")

        RUNNER_ID=$(echo "$response" | jq -r ".runners[] | select(.name == \"${{ inputs.runner_name }}\") | .id")

        IFS=',' read -ra LABELS <<< "${{ inputs.labels }}"
        for label in "${LABELS[@]}"; do
          curl -X DELETE -sS \
            -H "Authorization: token ${{ inputs.gh_token }}" \
            "https://api.github.com/orgs/taosdata/actions/runners/$RUNNER_ID/labels/${label// /%20}" \
            -o /dev/null
        done