name: Install Nginx
description: Install Nginx And Start Service

inputs:
  nginx_port:
    description: 'Listening port (default 80)'
    required: false
    default: '80'

runs:
  using: 'composite'
  steps:
    - name: Install Nginx
      shell: bash
      run: |
        script_path=$(find $GITHUB_WORKSPACE/../../ -name install_nginx.sh 2>/dev/null | head -n 1)
        chmod +x $script_path
        $script_path "${{ inputs.nginx_port }}"