name: Update Variable
description: Updates the repository variable value.

inputs:
  github-token:
    description: 'GitHub token with repo scope'
    required: true
  repo-name:
    description: 'Repository name'
    required: true
  variable-name:
    description: 'Variable name to update'
    required: true
  variable-value:
    description: 'New value for the variable'
    required: true

runs:
  using: "composite"
  steps:
    - name: Update repository variable
      shell: bash
      run: |
        curl -X PATCH \
          -H "Authorization: token ${{ inputs.github-token }}" \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Content-Type: application/json" \
          "https://api.github.com/repos/${{ inputs.repo-name }}/actions/variables/${{ inputs.variable-name }}" \
          -d '{"name":"${{ inputs.variable-name }}","value":"${{ inputs.variable-value }}"}'
