name: 'Update Process Exporter YAML'
description: 'Update YAML file from process names'
inputs:
  yml_file_path:
    description: 'Path Of YAML file'
    required: true
  process_names:
    description: 'Comma-separated list of process names to monitor'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Update Process Exporter YAML
      shell: bash
      run: |
        # Check the number of parameters
        if [ "${{ inputs.yml_file_path }}" == "" ] || [ "${{ inputs.process_names }}" == "" ]; then
          echo "Usage: <yml_file_path> <process_name1,process_name2,...>"
          exit 1
        fi

        # Get parameters
        yml_file_path="${{ inputs.yml_file_path }}"
        PROCESS_NAMES="${{ inputs.process_names }}"

        # Convert process names into an array
        IFS=',' read -r -a NAMES_ARRAY <<< "$PROCESS_NAMES"

        # Create the YAML file and write the content
        cat << EOF > "$yml_file_path"
process_names:
EOF

        # Write each process name
        for NAME in "${NAMES_ARRAY[@]}"; do
          cat << EOF >> "$yml_file_path"
- cmdline:
  - $NAME
  name: '{{.Comm}}'
EOF
        done

        echo "YAML file updated: $yml_file_path"

    - name: Restart and Check process-exporter Status
      shell: bash
      run: |
        # Restart process-exporter
        systemctl restart process_exporter
        # Check process-exporter status
        STATUS=$(systemctl is-active process_exporter)
        if [ "$STATUS" != "active" ]; then
          echo "::error ::ERROR: process-exporter is in $STATUS state."
          exit 1
        else
          echo "process-exporter is running successfully."
        fi