name: Install TDengine Enterprise

inputs:
  version:
    required: true
    type: string
    description: 'Version number, e.g., 3.3.5.1'
  group:
    required: true
    type: string
    description: 'Group, e.g., fractal'
  labels:
    required: true
    type: string
    description: 'Labels, e.g., self-hosted, Linux, X64, fractal, edge_td, fractal-edge-1'

jobs:
  install-tdengine:

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up variables
      run: |
        VERSION=${{ inputs.version }}
        GROUP=${{ inputs.group }}
        BASE_URL=${{ secrets.NAS_DOWNLOAD_URL }}

        # Get major version
        MAJOR_VERSION=$(echo $VERSION | cut -d '.' -f 1-2)

        # Get download URL
        URL="${BASE_URL}/${MAJOR_VERSION}/v${VERSION}/enterprise/TDengine-enterprise-${VERSION}-Linux-x64.tar.gz"
        echo "Download URL: $URL"
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        echo "GROUP=$GROUP" >> $GITHUB_ENV
        echo "URL=$URL" >> $GITHUB_ENV

    - name: Download TDengine
      run: |
        wget $URL

    - name: Extract TDengine
      run: |
        tar -xzvf TDengine-enterprise-${VERSION}-Linux-x64.tar.gz

    - name: Install TDengine
      run: |
        cd TDengine-enterprise-${VERSION}
        yes | ./install.sh