name: Install Mysql
description: Install Mysql And Start Service

inputs:
  mysql_version:
    description: 'Mysql version to install'
    required: false
    default: '8.0'

runs:
  using: 'composite'
  steps:
    - name: Install Mysql
      shell: bash
      run: |
        sudo ${GITHUB_ACTION_PATH}/../../scripts/install_mysql.sh "${{ inputs.mysql_version }}"