name: Install TDengine Enterprise
description: Install TDengine Enterprise and start the service
inputs:
  version:
    required: true
    description: 'Version number, e.g., 3.3.5.1'
  download_url:
    required: true
    description: 'A secrets'
  clean:
    required: false
    description: 'Whether to clean up old versions, default is false'
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Install TDengine Enterprise
      shell: bash
      run: |
        script_path=$(find $GITHUB_WORKSPACE/../../ -name install_tdengine_enterprise.sh 2>/dev/null | head -n 1)
        chmod +x $script_path
        $script_path "${{ inputs.version }}" "${{ inputs.download_url }}" "${{ inputs.clean }}"