name: 'Download TDasset Backend Package'
description: 'Download the TDasset backend package from GitHub Packages'
inputs:
  event_name:
    description: 'Event name that triggered the workflow'
    required: true
    default: 'workflow_dispatch'
  package_version:
    description: 'Version of the TDasset backend package to download'
    required: true
    default: 'latest'
  gh_token:
    description: 'GitHub access token'
    required: true

runs:
  using: "composite"
  steps:
    - name: Download TDasset Backend Package
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.gh_token }}
      run: |
        echo "Downloading TDasset backend package version: ${{ inputs.package_version }}"
        PACKAGE_NAME="tdasset-backend"
        PACKAGE_VERSION="${{ inputs.package_version }}"
        PACKAGE_URL="