name: Deploy taostest and TestNG
description: Deploy taostest and TestNG

inputs:
  taostest-dir:
    description: 'Parent directory for taos-test-framework repository'
    required: true
    default: '$RUNNER_WORKSPACE/../taos-test-framework'
  testng-dir:
    description: 'Parent directory for the TestNG repository'
    required: true
    default: '$RUNNER_WORKSPACE/../TestNG'

runs:
  using: 'composite'
  steps:
    # - name: Set up Python and dependencies
    #   shell: bash
    #   run: |
    #     apt-get update
    #     apt install -y python3-pip
    #     pip3 install poetry

    - name: Deploy taostest and TestNG
      shell: bash
      id: deploy-taostest-testng
      run: |
        TEST_ROOT=${{ inputs.testng-dir }}
        echo "TEST_ROOT=$TEST_ROOT" >> $GITHUB_ENV
        cd ${{ inputs.taostest-dir }}
        echo "Y" | bash reinstall.sh
        ENV_FILE=~/.taostest/.env
        mkdir -p ~/.taostest
        touch $ENV_FILE
        echo "TEST_ROOT==$TEST_ROOT" > $ENV_FILE
        echo "TAOSTEST_SQL_RECORDING_ENABLED=True" >> $ENV_FILE

    # - name: Install Python packages
    #   shell: bash
    #   run: pip3 install --upgrade numpy pandas

# outputs:
#   test_root:
#     description: 'Path to TEST_ROOT'
#     value: ${{ steps.deploy-taostest-testng.TEST_ROOT }}
