name: 'Download Artifacts'
description: 'Download all artifacts from current workflow run with GH CLI'
inputs:
  gh_token:
    description: 'GitHub access token'
    required: true
    default: 'A secret'
  download_dir:
    description: 'Directory to save artifacts'
    required: true
    default: 'artifacts'

runs:
  using: "composite"
  steps:
    - name: Authenticate And Download Artifacts
      shell: bash
      run: |
        echo "🔄 Authenticating GitHub CLI..."
        "${GITHUB_ACTION_PATH}/../../scripts/install_via_apt.sh" gh
        echo "${{ inputs.gh_token }}" | gh auth login --with-token
        echo "🔄 Downloading artifacts to: ${{ inputs.download_dir }}"
        rm -rf "${{ inputs.download_dir }}"
        mkdir -p "${{ inputs.download_dir }}"
        gh run download $GITHUB_RUN_ID --dir "${{ inputs.download_dir }}"