name: "Setup Flink"
description: "Start a specific version of Flink"

inputs:
  flink_version:
    description: "The version of Flink"
    required: false
    default: "1.17.2"
  scala_version:
    description: "The version of scala (default: 2.12)"
    required: false
    default: "2.12"
  java_version:
    description: "The version of scala (default: 11)"
    required: false
    default: "11"
  install_java:
    description: "Whether to install Java (default: true)"
    required: false
    default: "true"
  install_dir:
    description: "The directory to install Flink (default: /opt/flink)"
    required: false
    default: "/opt/flink"
  flink_user:
    description: "The user to run Flink (default: flink)"
    required: false
    default: "flink"

runs:
  using: 'composite'
  steps:
    - name: Install Flink
      shell: bash
      run: |
        sudo ${GITHUB_ACTION_PATH}/../../scripts/install_flink.sh "${{ inputs.flink_version }}" "${{ inputs.scala_version }}" "${{ inputs.java_version }}" "${{ inputs.install_java }}" "${{ inputs.install_dir }}" "${{ inputs.flink_user }}"
