name: Install Grafana
description: Install Grafana And Start Service

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Grafana And Enable Anonymous Access
      shell: bash
      run: |
        # Install And Start Grafana with setup_env.sh
        echo "current path: $PWD"
        wget -O setup_env.sh https://raw.githubusercontent.com/taosdata/TDengine/main/packaging/setup_env.sh
        chmod +x setup_env.sh
        ./setup_env.sh deploy_grafana
        # Enable Anonymous Access
        echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
        script_path=$(find $GITHUB_WORKSPACE/../../ -name config_grafana_anonymous_access.sh 2>/dev/null | head -n 1)
        $GITHUB_WORKSPACE
        chmod +x $script_path
        $script_path /etc/grafana/grafana.ini