name: Install Grafana
description: Install Grafana and start the service

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Check and Install Grafana
      shell: bash
      run: |
        # Install And Start Grafana with setup_env.sh
        wget -O setup_env.sh https://raw.githubusercontent.com/taosdata/TDengine/main/packaging/setup_env.sh
        chmod +x setup_env.sh
        ./setup_env.sh deploy_grafana
        # Enable Anonymous Access
        .github/scripts/config_grafana_anonymous_access.sh /etc/grafana/grafana.ini