name: Install Grafana
description: Install Grafana and start the service

runs:
  using: 'composite'
  steps:
  - name: Check and Install Grafana
    shell: bash
    run: |
      if dpkg -l | grep -q grafana; then
        echo "Grafana is already installed."
        # Check if Grafana is running
        if systemctl is-active --quiet grafana-server; then
          echo "Grafana is already running."
        else
          echo "Grafana is not running. Starting the service."
          systemctl start grafana-server
        fi
      else
        echo "Grafana is not installed. Proceeding with installation."
        # Install Grafana with setup_env.sh
        wget https://raw.githubusercontent.com/taosdata/TDengine/main/packaging/setup_env.sh
        chmod +x setup_env.sh
        ./setup_env.sh deploy_grafana
      fi

  - name: Check Grafana Status
    shell: bash
    run: |
      STATUS=$(systemctl is-active grafana-server)
      if [ "$STATUS" != "active" ]; then
        echo "::error ::ERROR: Grafana is in $STATUS state."
        exit 1
      else
        echo "Grafana is running successfully."
      fi