name: SSH Copy ID
description: Configure SSH keyless login to target hosts

inputs:
  target_hosts:
    description: 'Comma-separated list of target hosts'
    required: true
  password:
    description: 'SSH login password'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Install TDengine Enterprise
      shell: bash
      run: |
        script_path=$(find $GITHUB_WORKSPACE/../../ -name config_ssh_keyless_login.sh 2>/dev/null | head -n 1)
        chmod +x $script_path
        $script_path "${{ inputs.target_hosts }}" "${{ inputs.password }}"