name: Deploy MinIO

inputs:
  MINIO_ROOT_USER:
    required: true
    type: string
    description: 'MINIO_ROOT_USER, e.g., admin'
  MINIO_ROOT_PASSWORD:
    required: true
    type: string
    description: 'MINIO_ROOT_PASSWORD, e.g., admin123456'
  MINIO_ACCESS_KEY:
    required: true
    type: string
    description: 'MINIO_ACCESS_KEY, e.g., LbQ88Tub************'
  MINIO_SECRET_KEY:
    required: true
    type: string
    description: 'MINIO_SECRET_KEY, e.g., 7e7b1b1b************'

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy MinIO
      shell: bash
      run: |
        chmod +x .github/scripts/deploy_minio.sh
        .github/scripts/deploy_minio.sh "${{ inputs.MINIO_ROOT_USER }}" "${{ inputs.MINIO_ROOT_PASSWORD }}" "${{ inputs.MINIO_ACCESS_KEY }}" "${{ inputs.MINIO_SECRET_KEY }}"