name: 'Manage Runner Labels'
inputs:
  gh_token:
    description: 'GitHub access token'
    required: true
    default: 'A secret'
  operation_type:
    description: 'add/delete'
    required: true
    default: 'add'
  labels:
    description: 'Comma-separated labels'
    required: true
  runner_name:
    description: 'Runner name'
    required: true
  scope:
    description: 'Runner scope (org/repo)'
    default: 'org'
  target:
    description: 'Organization name or repo slug'
    default: 'taosdata'
runs:
  using: "composite"
  steps:
    - name: Manage Runner Labels
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      run: |
        # Validate scope and target format
        if [[ "${{ inputs.scope }}" == "repo" && "${{ inputs.target }}" != */* ]]; then
          echo "::error::Repo target must be in 'owner/repo' format"
          exit 1
        elif [[ "${{ inputs.scope }}" != "org" && "${{ inputs.scope }}" != "repo" ]]; then
          echo "::error::Invalid scope: must be 'org' or 'repo'"
          exit 1
        fi

        # Construct API URL
        if [[ "${{ inputs.scope }}" == "org" ]]; then
          api_url="https://api.github.com/orgs/${target}/actions/runners"
        else
          api_url="https://api.github.com/repos/${target}/actions/runners"
        fi
        echo "api_url---"
        echo $api_url
        response=$(curl -sS -H "Authorization: Bearer ${{ inputs.gh_token }}" "$api_url")

        RUNNER_ID=$(echo "$response" | jq -r ".runners[] | select(.name == \"${{ inputs.runner_name }}\") | .id")
        echo "runner id: $RUNNER_ID"

        case "${{ inputs.operation_type }}" in
          add)
            JSON_DATA=$(echo "${{ inputs.labels }}" | jq -R 'split(",")' | jq -c '{labels: .}')
            # Add labels to runner
            curl -X POST -sS \
              -H "Authorization: token ${{ inputs.gh_token }}" \
              -H "Accept: application/vnd.github.v3+json" \
              "$api_url/$RUNNER_ID/labels" \
              -d "$JSON_DATA"

            echo "Added labels: ${{ inputs.labels }}"
            ;;

          delete)
            IFS=',' read -ra LABELS <<< "${{ inputs.labels }}"
            for label in "${LABELS[@]}"; do
              curl -X DELETE -sS \
                -H "Authorization: token ${{ inputs.gh_token }}" \
                "$api_url/$RUNNER_ID/labels/${label// /%20}" \
                -o /dev/null

              echo "Deleted label: $label"
            done
            ;;
        esac
