name: Call Install TDengine Enterprise

on:
  push:
    branches:
      - test/fractal

jobs:

  call-install:
    runs-on:
      group: fractal
      labels: [self-hosted, Linux, X64, fractal, edge_td, fractal-edge-1]
    steps:
      - name: Check and Install FlashMQ
        uses: taosdata/.github/.github/actions/install-tdengine@test/fractal
        with:
          version: 3.3.5.1
          group: fractal
          labels: '[self-hosted, Linux, X64, fractal, edge_td, fractal-edge-1]'
          secrets: ${{ secrets.NAS_DOWNLOAD_URL }}
