name: Clean TDasset Packages

on:
  workflow_call:
    inputs:
      paackage_type:
        description: "npm or maven, or all"
        required: true
        type: string
        default: 'all'
      keep_days:
        description: "The number of days to keep the package"
        required: true
        type: string
        default: '10'

jobs:
  clean-frontend-packages:
    runs-on: ubuntu-latest
    if: ${{ inputs.paackage_type == 'npm' || inputs.paackage_type == 'all' }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          repository: 'taosdata/.github'
          ref: 'ci/tdasset'
          fetch-depth: 0

      - name: Clean frontend packages
        run: |
          PACKAGE_SCOPE="taosdata"
          PACKAGE_NAME="tdasset-frontend"
          chmod +x ./.github/scripts/clean_tdasset_packages.sh

          echo "Cleaning NPM Package: @${PACKAGE_SCOPE}/${PACKAGE_NAME}"
          ./.github/scripts/clean_tdasset_packages.sh \
              -t "npm" \
              -n "$PACKAGE_NAME" \
              -s "$PACKAGE_SCOPE" \
              -d ${{ inputs.keep_days }} \
              -a ${{ secrets.WORKFLOW_WRITE_PAT }}

  clean-backend-packages:
    runs-on: ubuntu-latest
    if: ${{ inputs.paackage_type == 'maven' || inputs.paackage_type == 'all' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Clean backend packages
        run: |
          PACKAGE_SCOPE="taosdata"
          BACKEND_PACKAGE_NAME="tdasset-backend"
          chmod +x ./.github/scripts/clean_tdasset_packages.sh

          echo "Cleaning Maven Package: ${BACKEND_PACKAGE_NAME}"
          ./.github/scripts/clean_tdasset_packages.sh \
              -t "maven" \
              -n "$BACKEND_PACKAGE_NAME" \
              -s "$PACKAGE_SCOPE" \
              -d ${{ inputs.keep_days }} \
              -a ${{ secrets.WORKFLOW_WRITE_PAT }}

          STANDALONE_PACKAGE_NAME="tdasset-standalone"

          echo "Cleaning Maven Package: ${STANDALONE_PACKAGE_NAME}"
          ./.github/scripts/clean_tdasset_packages.sh \
              -t "maven" \
              -n "$STANDALONE_PACKAGE_NAME" \
              -s "$PACKAGE_SCOPE" \
              -d ${{ inputs.keep_days }} \
              -a ${{ secrets.WORKFLOW_WRITE_PAT }}

          LIB_PACKAGE_NAME="tdasset-lib"

          echo "Cleaning Maven Package: ${LIB_PACKAGE_NAME}"
          ./.github/scripts/clean_tdasset_packages.sh \
              -t "maven" \
              -n "$LIB_PACKAGE_NAME" \
              -s "$PACKAGE_SCOPE" \
              -d ${{ inputs.keep_days }} \
              -a ${{ secrets.WORKFLOW_WRITE_PAT }}
