name: deploy-mqttcli

on:
  workflow_dispatch:
    inputs:
      runner_number:
        description: 'Runner number (1-2)'
        required: true
        type: choice
        options:
          - 1
          - 2


jobs:
  set-runners:
    runs-on: ubuntu-latest
    outputs:
      mqtt_clients: ${{ steps.set-mqtt-clients.outputs.mqtt_clients }}
      fractal_edges: ${{ steps.set-fractal-edges.outputs.fractal_edges }}
    steps:
      - name: Set MQTT Clients
        id: set-mqtt-clients
        run: |
          echo "Setting MQTT Clients"
          clients=$(seq -s ',' 1 ${{ github.event.inputs.runner_number }} | sed 's/[0-9]\+/mqtt-client&/g')
          clients_json=$(echo -n $clients | jq -R -s -c 'split(",")')
          echo "::set-output name=mqtt_clients::$clients_json"

      - name: Set Fractal Edges
        id: set-fractal-edges
        run: |
          echo "Setting Fractal Edges"
          edges=$(seq -s ',' 1 ${{ github.event.inputs.runner_number }} | sed 's/[0-9]\+/fractal-edge-&/g')
          edges_json=$(echo -n $edges | jq -R -s -c 'split(",")')
          echo "::set-output name=fractal_edges::$edges_json"

  run-on-mqtt-client:
    needs: set-runners
    strategy:
      matrix:
        runner: ${{ fromJSON(needs.set-runners.outputs.mqtt_clients) }}
    runs-on: 
      group: fractal
      labels: self-hosted, Linux, X64, fractal, edge_td, ${{ matrix.runner }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run a script on MQTT Clients
        run: echo "Running on ${{ runner.name }}"

  run-on-fractal-edge:
    needs: set-runners
    strategy:
      matrix:
        runner: ${{ fromJSON(needs.set-runners.outputs.fractal_edges) }}
    runs-on: 
      group: fractal
      labels: self-hosted,Linux,X64,edge_td,fractal,${{ matrix.runner }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run a script on Fractal Edges
        run: echo "Running on ${{ runner.name }}"