name: Deploy MinIO

# on:
#   workflow_dispatch:
on:
  push:
    branches:
      - test/fractal

jobs:
  call-install:
    runs-on:
      group: fractal
      labels: [self-hosted, Linux, X64, fractal, edge_td, fractal-edge-1]

    steps:
      - name: Check and Deploy MinIO
        uses: taosdata/.github/.github/actions/deploy-minio@test/fractal
        with:
          MINIO_ROOT_USER: ${{ secrets.MINIO_ROOT_USER }}
          MINIO_ROOT_PASSWORD: ${{ secrets.MINIO_ROOT_PASSWORD }}
          MINIO_ACCESS_KEY: ${{ secrets.MINIO_ACCESS_KEY }}
          MINIO_SECRET_KEY: ${{ secrets.MINIO_SECRET_KEY }}