name: Install FlashMQ

# on:
#   workflow_call:

on:
  push:
    branches:
      - test/fractal

jobs:
  install-flashmq:
    runs-on:
        group: fractal
        labels: [self-hosted, Linux, X64, fractal, edge_td, fractal-edge-2]

    steps:
    - name: Check and Install FlashMQ
      run: |
        if dpkg -l | grep -q flashmq; then
          echo "FlashMQ is already installed."
          # Check if FlashMQ is running
          if systemctl is-active --quiet flashmq; then
            echo "FlashMQ is already running."
          else
            echo "FlashMQ is not running. Starting the service."
            systemctl start flashmq
          fi
        else
          echo "FlashMQ is not installed. Proceeding with installation."
          # Add FlashMQ GPG Key
          curl https://www.flashmq.org/wp-content/uploads/2021/10/flashmq-repo.gpg > /usr/share/keyrings/flashmq-repo.gpg

          # Add FlashMQ APT Repository
          echo "deb [signed-by=/usr/share/keyrings/flashmq-repo.gpg] http://repo.flashmq.org/apt $(lsb_release -cs) main" > /etc/apt/sources.list.d/flashmq.list

          # Update Package List and Install FlashMQ
          apt update -y && apt install -y flashmq

          # Start FlashMQ and Enable on Startup
          systemctl start flashmq
          systemctl enable flashmq
        fi

    - name: Check FlashMQ Status
      run: |
        STATUS=$(systemctl is-active flashmq)
        if [ "$STATUS" != "active" ]; then
          echo "::error ::ERROR: FlashMQ is in $STATUS state."
          exit 1
        else
          echo "FlashMQ is running successfully."
        fi