name: Install TDengine Enterprise

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Enter the version of TDengine to install'
        required: true
        default: '3.3.5.1'
      group:
        description: 'Enter the group for the runner'
        required: true
        default: 'fractal'
      labels:
        description: 'Enter the labels for the runner'
        required: true
        default: '[self-hosted, Linux, X64, fractal, edge_td, fractal-edge-1]'

jobs:
  call-install:
    runs-on:
      group: ${{ github.event.inputs.group }}
      labels: ${{ fromJson(github.event.inputs.labels) }}
    steps:
      - name: Check and Install TDengine Enterprise
        uses: taosdata/.github/.github/actions/install-tdengine@main
        with:
          version: ${{ github.event.inputs.version }}
          group: ${{ github.event.inputs.group }}
          labels: ${{ github.event.inputs.labels }}
          nas_download_url: ${{ secrets.NAS_DOWNLOAD_URL }}
