name: Install FlashMQ

# on:
#   workflow_dispatch:
on:
  push:
    branches:
      - test/fractal

jobs:
  install-flashmq:
    runs-on:
      group: fractal
      labels: [self-hosted, Linux, X64, fractal, center_td, fractal-center-1]

    steps:
      - name: Check and Deploy MinIO
        uses: taosdata/.github/.github/actions/install-flashmq@test/fractal