name: TDengine Coverage (taosd & taosc)
description: Reusable Workflow for taosd & taosc coverage test

on:
  workflow_call:
    inputs:
      specified_tdinternal_test_branch:
        description: 'Enter the test branch of TDinternal'
        required: true
        type: string
      specified_tdengine_test_branch:
        description: 'Enter the test branch of TDengine'
        required: true
        type: string

jobs:
  validate_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Get all changed case files
        id: changed-case-files
        uses: tj-actions/changed-files@v45
        with:
          files: |
            test/cases/**/test_*.py

      - name: Validate test files
        if: steps.changed-case-files.outputs.any_changed == 'true'
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-case-files.outputs.all_changed_files }}
        run: |
          EXIT_CODE=0
          for file in ${ALL_CHANGED_FILES}; do
            echo "$file was changed"
            python .github/scripts/validate_tests.py "$file" || EXIT_CODE=1
          done
          exit $EXIT_CODE

  run-tests:
    strategy:
      fail-fast: false
      matrix:
        #platform: [linux, macos, windows]
        platform: [linux]
        include:
          - platform: linux
            runner_group: CI
            runner_labels: [self-hosted, Linux, X64, new-framework]
            WKDIR: '/var/lib/jenkins/workspace'
            WK: '/var/lib/jenkins/workspace/TDinternal'
            WKC: '/var/lib/jenkins/workspace/TDinternal/community'
          # - platform: macos
          #   runner_group: CI
          #   runner_labels: [self-hosted, macOS, X64, testing]
          #   WKDIR: '/var/lib/jenkins/workspace'
          #   WK: '/var/lib/jenkins/workspace/TDinternal'
          #   WKC: '/var/lib/jenkins/workspace/TDinternal/community'
          # - platform: windows
          #   runner_group: CI
          #   runner_labels: [self-hosted, Windows, X64, test-win]
          #   WKDIR: 'C:\\workspace\\0'                 # adjust as needed for your windows runners
          #   WK: 'C:\\workspace\\0\\TDinternal'
          #   WKC: 'C:\\workspace\\TDinternal\\community'
    runs-on:
      group: ${{ matrix.runner_group }}
      labels: ${{ matrix.runner_labels }}

    needs: validate_tests

    timeout-minutes: 200

    env:
      CONTAINER_NAME: 'taosd-test'
      WKDIR: ${{ matrix.WKDIR }}
      WK: ${{ matrix.WK }}
      WKC: ${{ matrix.WKC }}
      IS_TDINTERNAL: ${{ inputs.tdinternal }}
      CURRENT_PLATFORM: ${{ matrix.platform }}
      TARGET_BRANCH: ${{ inputs.specified_target_branch }}
      PYTHONIOENCODING: utf-8
      PYTHONUTF8: "1"
      LANG: en_US.UTF-8      

    defaults:
      run:
        working-directory: ${{ github.workspace }}/.github/scripts/

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          repository: 'taosdata/.github'
          ref: 'test/td-37719'
          fetch-depth: 0

      - name: Prepare the environment
        run: python3 prepare.py
        env:
          WKDIR: ${{ env.WKDIR }}
          IS_TDINTERNAL: ${{ inputs.tdinternal }}
          GITHUB_RUN_NUMBER: ${{ github.run_number }}
          CONTAINER_NAME: ${{ env.CONTAINER_NAME }}
          GITHUB_EVENT: ${{ toJson(github.event) }}
          GITHUB_INPUTS: ${{ toJson(inputs) }}

      - name: Check assert testing
        if: >
          env.IS_TDINTERNAL == 'false' &&
          env.TARGET_BRANCH != '3.1' &&
          matrix.platform == 'linux'
        run: python3 test.py
        env:
          WKDIR: ${{ env.WKDIR }}
          TEST_TYPE: 'assert'
  
      - name: Check void function testing
        if: >
          env.IS_TDINTERNAL == 'false' &&
          env.TARGET_BRANCH != '3.1' &&
          matrix.platform == 'linux'
        run: python3 test.py
        env:
          TEST_TYPE: 'void'

      - name: Build docker or repo
        run: python3 build.py
        env:
          BUILD_TYPE: ${{ matrix.platform == 'linux' && 'docker' || 'repo' }}

      - name: Run function returns with a null pointer scan testing
        if: >
          env.IS_TDINTERNAL == 'false' &&
          env.TARGET_BRANCH != '3.1' &&
          matrix.platform == 'linux'
        run: python3 test.py
        env:
          TEST_TYPE: 'function_returns'

      - name: Run function test cases
        run: python3 test.py
        env:
          TEST_TYPE: 'function'
        continue-on-error: true

      - name: Run coverage test 
        if: >
            env.IS_TDINTERNAL == 'false' &&
            env.TARGET_BRANCH != '3.1' &&
            env.TARGET_BRANCH != '3.3.6' &&
            matrix.platform == 'linux'
        run: python3 test.py
        env:
          TEST_TYPE: 'coverage'
          PR_NUMBER: ${{ github.event.pull_request.number }}
          GITHUB_RUN_NUMBER: ${{ github.run_number }}